# Generated by Django 2.1.7 on 2019-03-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tollgatedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(default='hiiiii', max_length=100)),
                ('vehiclename', models.CharField(default='BIKE', max_length=100)),
                ('src', models.CharField(default='hello', max_length=20)),
                ('dest', models.CharField(default='keew', max_length=40)),
                ('charge', models.IntegerField(default='h6')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 24, 0, 49, 43, 552964))),
                ('journy', models.CharField(default='single', max_length=50)),
            ],
        ),
    ]
