# Generated by Django 2.1.7 on 2019-03-24 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190324_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollgatedb',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 24, 11, 3, 46, 297967)),
        ),
    ]
