# Generated by Django 2.1.7 on 2019-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindb1',
            fields=[
                ('username', models.CharField(default='hiiiii', max_length=100, primary_key='true', serialize=False)),
                ('password', models.CharField(default='hello', max_length=20)),
                ('location', models.CharField(default='keew', max_length=40)),
                ('lane', models.CharField(max_length=50, unique='true')),
            ],
        ),
    ]
