# Generated by Django 2.1.7 on 2019-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updatedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(default='hiiiii', max_length=100)),
                ('amount', models.IntegerField(default=50)),
            ],
        ),
    ]
